### ISSUE TITLE
Filename too long 

### ISSUE THREAD

**Issue by ssumit555** [OxMohsen/uniquify-bot#1]
It always saying filename too long, i already generated string session 4 times 
![IMG_20220723_231607_390](https://user-images.githubusercontent.com/54541071/180616857-eeed6540-92cb-4a7f-9231-84f94eb7ff10.jpg)

**Comment by OxMohsen** [comment]
you must pass shorter name for your session name like `mybot`.
i will add using `session_string`.

**Comment by OxMohsen** [comment]
it's ok now, you can load account with session string too.
